@baseURL = http://localhost:3000
@warriors = {{baseURL}}/warriors
@appointments = {{baseURL}}/appointments
@healers = {{baseURL}}/healers

###

GET {{warriors}}

###

GET {{healers}}

###

@nickname = CUR_7e0c2851-c97c-4030-8b13-4f3422ca482f

GET {{healers}}/{{nickname}}/availability
  ?date=2023-02-25

###

POST {{warriors}}
Content-Type: application/json

{
  "name": "name",
  "surname": "surname"
}

###


POST {{healers}}
Content-Type: application/json

{
  "name": "name",
  "surname": "surname",
  "onlineBetween": [
    { "hour": 6, "minute": 0 },
    { "hour": 18, "minute": 0 }
  ]
}

###

POST {{appointments}}
Content-Type: application/json

{
  "end": { "hour": 0, "minute": 0 },
  "start": { "hour": 17, "minute": 0 },
  "date": "2023-03-25",
  "healerNickname": "CUR_7e0c2851-c97c-4030-8b13-4f3422ca482f",
  "warriorNickname": "GUR_021bfa94-a1ce-4c6b-b35b-2f18b522299e"
}
